version: 0.1

phases:
  build:
    commands:
      - echo Build Started Successfully
      - mvn clean package
    post_build:
      commands:
        - echo Build Completed Successfully

artifacts:
  files:
    - target/fub-v1.jar
  discard-paths: yes